### ISSUE TITLE
Lablgtk problem (cygwin64, windows 10, x86_64-w64-mingw32)

### ISSUE THREAD

**Issue by fithisux** [fdopen/opam-repository-mingw#10]
orbit@gopro-pc ~
$ opam depext -i lablgtk
# Detecting depexts using flags: x86_64 mswindows win32 cygwinports
# The following system packages are needed:
#  - gtk2.0
#  - pkg-config
installed:gtk2.0
installed:pkg-config
# All required OS packages found.
The following actions will be performed:
  ∗  install lablgtk 2.18.3

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[lablgtk: http] Command started
[lablgtk.2.18.3] https://forge.ocamlcore.org/frs/download.php/1479/lablgtk-2.18.3.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[lablgtk: ./configure] Command started
[ERROR] The compilation of lablgtk failed at "./configure --prefix
        C:/langs/home/.opam/4.02.3+mingw64
        LABLGLDIR=C:/langs/home/.opam/4.02.3+mingw64/lib/lablgl".
[lablgtk: ocamlfind remove] Command started

#=== ERROR while compiling lablgtk.2.18.3 =====================================#
# opam-version         1.3.0~dev (308be376d177c155c1f7f86a8ffaf621c9029836)
# os                   win32
# command              ./configure --prefix C:/langs/home/.opam/4.02.3+mingw64 LABLGLDIR=C:/langs/home/.opam/4.02.3+mingw64/lib/lablgl
# path                 C:/langs/home/.opam/4.02.3+mingw64/build/lablgtk.2.18.3
# exit-code            1
# env-file             C:/langs/home/.opam/4.02.3+mingw64/build/lablgtk.2.18.3\lablgtk-372-d2d111.env
# stdout-file          C:/langs/home/.opam/4.02.3+mingw64/build/lablgtk.2.18.3\lablgtk-372-d2d111.out
# stderr-file          C:/langs/home/.opam/4.02.3+mingw64/build/lablgtk.2.18.3\lablgtk-372-d2d111.err
### stdout ###
# [...]
# checking native dynlink... checking for pkg-config... /cygdrive/c/langs/home/.opam/4.02.3+mingw64/bin/pkg-config
# checking for GTK+ - version >= 2.0.0... no
# *** Could not run GTK+ test program, checking why...
# *** The test program compiled, but did not run. This usually means
# *** that the run-time linker is not finding GTK+ or finding the wrong
# *** version of GTK+. If it is not finding GTK+, you'll need to set your
# *** LD_LIBRARY_PATH environment variable, or edit /etc/ld.so.conf to point
# *** to the installed location  Also, make sure you have run ldconfig if that
# *** is required on your system
# ***
# *** If you have an old version installed, it is best to remove it, although
# *** you may also be able to get things to work by modifying LD_LIBRARY_PATH
### stderr ###
# configure: error: GTK+ is required

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  λ  build lablgtk 2.18.3
No changes have been performed

=-=- lablgtk.2.18.3 troubleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package requires gtk+ 2.0 development packages installed on your system
# Now letting OPAM install the packages

**Comment by fithisux** [comment]
orbit@gopro-pc ~
$ which pkg-config
/cygdrive/c/langs/home/.opam/4.02.3+mingw64/bin/pkg-config

orbit@gopro-pc ~
$ pkg-config --libs gtk+-2.0
-lgtk-win32-2.0 -lgdk-win32-2.0 -lgdi32 -limm32 -lshell32 -lole32 -Wl,-luuid -lpangocairo-1.0 -lpangoft2-1.0 -lharfbuzz -lpangowin32-1.0 -lgdi32 -lusp10 -lpango-1.0 -lm -latk-1.0 -lcairo -lz -lpixman-1 -lfontconfig -lexpat -lfreetype -lbz2 -lz -lpng16 -lz -lexpat -lfreetype -lbz2 -lz -lpng16 -lz -lgdk_pixbuf-2.0 -lpng16 -lz -lgio-2.0 -lz -lgmodule-2.0 -lgobject-2.0 -lffi -lglib-2.0 -lintl -lws2_32 -lole32 -lwinmm -lshlwapi -lintl

orbit@gopro-pc ~
$ pkg-config --cflags gtk+-2.0
-mms-bitfields -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/gtk-2.0 -I/usr/x86_64-w64-mingw32/sys-root/mingw/lib/gtk-2.0/include -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/pango-1.0 -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/harfbuzz -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/pango-1.0 -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/cairo -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/atk-1.0 -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/cairo -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/pixman-1 -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/freetype2 -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/libpng16 -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/freetype2 -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/libpng16 -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/gdk-pixbuf-2.0 -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/libpng16 -I/usr/x86_64-w64-mingw32/sys-root/mingw/include/glib-2.0 -I/usr/x86_64-w64-mingw32/sys-root/mingw/lib/glib-2.0/include

orbit@gopro-pc ~

**Comment by fdopen** [comment]
Have you added `/usr/x86_64-w64-mingw32/sys-root/mingw/bin` to your PATH? (see: https://fdopen.github.io/opam-repository-mingw/depext-cygwin/ )

**Comment by fithisux** [comment]
I stand corrected.
