### ISSUE TITLE
Why was my package marked as unavailable on windows?

### ISSUE THREAD

**Issue by phated** [fdopen/opam-repository-mingw#101]
Ref https://github.com/fdopen/opam-repository-mingw/commit/c3156f00354525d19c312614b812933799575f00

I put a lot of time into ensuring libbinaryen can be built on windows. You can check our Opam CI run: https://github.com/grain-lang/libbinaryen/runs/4169764338?check_suite_focus=true

We are specifically building this package to be compatible with all OS & architectures.

**Comment by fdopen** [comment]
It doesn't work with the cmake shipped by cygwin (no proper configuration for cross-compiling), it only works on the Opam CI because another version of cmake is picked up.

**Comment by phated** [comment]
Ah, interesting. I didn't know that. I'm not too familiar with this stack—is that something I can fix in my dune file?

**Comment by phated** [comment]
This was solved by https://github.com/grain-lang/libbinaryen/pull/34
