### ISSUE TITLE
opam install menhir fails

### ISSUE THREAD

**Issue by neolem** [fdopen/opam-repository-mingw#15]
`opam install menhir` fails with the error `install: cannot create regular file '/home/foo/.opam/system/bin/menhir': File exists`

**Comment by fdopen** [comment]
You are using the wrong opam build. Please use the opam build linked here: https://github.com/fdopen/opam-repository-mingw/blob/master/README.md#download

**Comment by neolem** [comment]
yep this did the trick for me. thanks. :+1:
