### ISSUE TITLE
opam lint warning

### ISSUE THREAD

**Issue by samoht** [fdopen/opam-repository-mingw#17]
I see these warnings when running the installed opam on a valid opam file (with a dev-repo field ending by `.git`):

```
Errors found in C:/projects/ocaml-ci-scripts/opam:
            error 42: The 'dev-repo' field doesn't use version control. You may
              use URLs of the form "git+https://" or a ".hg" or ".git" suffix
```

I know these were present in some dev versions of opam but should now be fixed. Would it be possible to use a fixed version?

**Comment by fdopen** [comment]
Ok, I've updated opam32.tar.xz and opam64.tar.xz. I think it was fixed with https://github.com/ocaml/opam/commit/5552f677b158387fe3c994aa31daa9e9a2be5e29 . If this doesn't solve your issue, please link an opam file.

**Comment by samoht** [comment]
Seems to work fine now, thanks for the quick reaction!
