### ISSUE TITLE
merlin package: sh.exe invocation failure

### ISSUE THREAD

**Issue by let-def** [fdopen/opam-repository-mingw#18]
This issue the-lambda-church/merlin#532 seems related to a failure of sh.exe:
```
merlin: sh.exe if [ ! -f ocamlmerlin.exe ] ; then cp -p ocamlmerlin_*.exe ocamlmerlin.exe; fi ] Command started
...
# bash: -c: line 0: syntax error near unexpected token `then'
# bash: -c: line 0: `sh.exe -c if [ ! -f ocamlmerlin.exe ] ; then cp -p ocamlmerlin_*.exe ocamlmerlin.exe; fi '
```

If I had to guess, I would say that there is not enough escaping, or too much nesting (sh.exe is already invoked from bash, maybe this layer can be removed?).

Anyway you are doing an awesome work for Windows. I would be happy to integrate patches upstream to ease that task.

**Comment by fdopen** [comment]
@schmavery should use the opam version linked here (for this repo): https://github.com/fdopen/opam-repository-mingw#download or here https://fdopen.github.io/opam-repository-mingw/installation/ 
Then the installation should work as expected, I've tested it when I've changed the opam file and just now again.

**Comment by Schmavery** [comment]
Okay, thanks for the tip.  I was trying to use http://protz.github.io/ocaml-installer/
Lots of ways to do this... hard for me to keep them all straight.  I will try your suggestion.  Thanks @let-def for referring my issue along :)

**Comment by Schmavery** [comment]
Update: this solution was successful.  Thanks for the help everyone :smile:

**Comment by let-def** [comment]
Nice to here. @fdopen: don't hesitate if you think patching upstream is appropriate.
