### ISSUE TITLE
Permission problem in installation

### ISSUE THREAD

**Issue by ignaciocaamanio** [fdopen/opam-repository-mingw#21]
$ bash opam64/install.sh produce this error:

```
mkdir : cannot create directory «/usr/local/include»: Permission denied 
mkdir : cannot create directory «/usr/local/lib/flexdll»: Permission denied
```

Do I have to change the permission of /usr/local ?

**Comment by fdopen** [comment]
You can also choose a different installation prefix and modify your PATH accordingly (But re-download `opam64.tar.xz`. There was indeed a small error in the script that could prevent the installation to another prefix):

```bash
mkdir ~/opam
bash opam64/install.sh --prefix ~/opam
export PATH=~/opam/bin:"$PATH"
opam init --comp 4.02.3+mingw64 --switch 4.02.3+mingw64
```
And note that `depext-cygwinports` won't work, if you don't have write access to `/usr`. If you need external dependencies like gtk2+ or gmp, you must install it manually with cygwin's setup tool.
