### ISSUE TITLE
GH pages. Link to depext part is broken

### ISSUE THREAD

**Issue by Kakadu** [fdopen/opam-repository-mingw#22]
On the page https://fdopen.github.io/opam-repository-mingw/installation/ .
Link at the bottom leads to https://fdopen.github.io/depext-cygwin (which is 404).
Right one is https://fdopen.github.io/opam-repository-mingw/depext-cygwin/ .

**Comment by fdopen** [comment]
Thanks for the hint, fixed with a90bb6eca6019434a738d33e56d847b1765c116b
