### ISSUE TITLE
Hosting installers on github instead of dropbox

### ISSUE THREAD

**Issue by andyli** [fdopen/opam-repository-mingw#26]
I would like to use the installer in a CI environment.
While it works nicely at the moment, in the past, I had issues with using dropbox for hosting dependencies, caused by the download limit (P.S. there were only ~10 builds per day).
Would you use [github release](https://help.github.com/articles/creating-releases/) instead? You can attach arbitrary files to a release.

**Comment by fdopen** [comment]
I'm aware of this problem and already moved many binaries to bintray.com (see 6180653150ab51388730f9dce8185ed82c050465 ).

However, I didn't move opam32.tar.xz and opam64.tar.xz. They need stable URLs that don't change every time the archives are updated (They are changed frequently, when either opam, flexlink, aspcud are updated - or the install scripts; the Cygwin distribution is a rolling release, unexpected changes can happen at any time). Bintray doesn't seem to support this. Already uploaded binaries can't be changed after a certain amount of time. You can only re-upload them to different URLs.

I've now created https://github.com/fdopen/opam-repository-mingw/releases/tag/0.0.0.1 . But I'm not sure if I can still replace the binaries in three or six months...

**Comment by fdopen** [comment]
I've replaced now all dropbox links with links to https://github.com/fdopen/opam-repository-mingw/releases/tag/0.0.0.1 now. The old links will however continue to work.
