### ISSUE TITLE
curl   I can't proceed :(

### ISSUE THREAD

**Issue by mohanr** [fdopen/opam-repository-mingw#27]
Isn't curl installed ? 

`

     476458@LT032871 /cygdrive/d/Ocaml/Week 6/ocaml
     $ bash opam64/install.sh
      the following programs are not installed properly:
       curl
      I can't proceed :(

      476458@LT032871 /cygdrive/d/Ocaml/Week 6/ocaml
      $ curl
      curl: try 'curl --help' or 'curl --manual' for more information

`

**Comment by fdopen** [comment]
Can you post the output of `curl --insecure --retry 2 --head "https://github.com"`  and `cygcheck -c`

**Comment by mohanr** [comment]
No problem. HTTP_PROXY was set as env. property. Removed. it.

**Comment by mohanr** [comment]
No problem. HTTP_PROXY was set as env. property. Removed. it.
