### ISSUE TITLE
issue with diffutils.3.5-2

### ISSUE THREAD

**Issue by samoht** [fdopen/opam-repository-mingw#30]
It seems that `install.sh` fails to detect `diff` installed by `diffutils.3.5-2` (but it works well with `diffutils.3.5-1`). Not sure where the issue actually comes from, but it causes our appveyor setups to fail.

e.g. https://github.com/ocaml/ocaml-ci-scripts/blob/master/appveyor-opam.sh#L36 fails with https://ci.appveyor.com/project/docker/datakit/build/1.0.815 

```
the following programs are not installed properly:
 diff
I can't proceed :(
```

**Comment by fdopen** [comment]
Probably because diffutils was build against a newer version of cygwin1.dll than the one that is already installed (I've not not tested it yet).

Try to add `-P cygwin` or remove `-P diffutils` from https://github.com/docker/datakit/blob/d3ed07cf415c5b0803f95272364dd22eadee07f6/appveyor.yml#L13

**Comment by samoht** [comment]
Thanks, removing `diffutils` worked!
