### ISSUE TITLE
cannot install compiler 4.01.0+mingw32c or compiler 4.01.0+mingw64c

### ISSUE THREAD

**Issue by nuaaysh** [fdopen/opam-repository-mingw#35]
i follow "https://fdopen.github.io/opam-repository-mingw/installation/" ,but i meet this problem (I must use this version) . anyone can help ? thanks very much!
the detail of this issue:
$ opam init mingw "https://github.com/fdopen/opam-repository-mingw.git" --comp 4     .01.0+mingw32c --switch 4.01.0+mingw32c
...
=-=- Fetching repository information =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[mingw: git]
[mingw: git]
[mingw: git]
[mingw: git]
[mingw: git]
[mingw: git]
[mingw] git+https://github.com/fdopen/opam-repository-mingw.git updated

=-=- Installing compiler 4.01.0+mingw32c =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[4.01.0+mingw32c: http]
[ERROR] https://dl.dropboxusercontent.com/s/q0z2httvdfsjaya/ocaml-4.01.0mingw32.     tar.xz
        is not available.
[ERROR] Initialisation failed
OpamStd.OpamSys.Exit(66)

**Comment by fdopen** [comment]
Hmm,

I can still access these files. Perhaps just a temporary failure of either your internet connection or dropbox.
But anyway, I've moved them to bintray.com now, too. (I've changed the host long time ago, because dropbox was slow and unreliable. But I but didn't bother to move the older versions...).

If it still doesn't work, you can also just try to compile this version from source, it will just take some time,...
```bash
opam init mingw "https://github.com/fdopen/opam-repository-mingw.git" --comp 4.01.0+mingw32 --switch 4.01.0+mingw32
```

**Comment by nuaaysh** [comment]
thanks very very ， i will try it tomorrow，



发自我的小米手机在 Andreas Hauptmann <notifications@github.com>，2017年7月23日 上午12:00写道：Hmm,
I can still access these files. Perhaps just a temporary failure of either your internet connection or dropbox.
But anyway, I've moved them to bintray.com now, too. (I've changed the host long time ago, because dropbox was slow and unreliable. But I but didn't bother to move the older versions...).
If it still doesn't work, you can also just try to compile this version from source, it will just take some time,...
opam init mingw "https://github.com/fdopen/opam-repository-mingw.git" --comp 4.01.0+mingw32 --switch 4.01.0+mingw32

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fdopen/opam-repository-mingw","title":"fdopen/opam-repository-mingw","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fdopen/opam-repository-mingw"}},"updates":{"snippets":[{"icon":"PERSON","message":"@fdopen in #35: Hmm,\r\n\r\nI can still access these files. Perhaps just a temporary failure of either your internet connection or dropbox.\r\nBut anyway, I've moved them to bintray.com now, too. (I've changed the host long time ago, because dropbox was slow and unreliable. But I but didn't bother to move the older versions...).\r\n\r\nIf it still doesn't work, you can also just try to compile this version from source, it will just take some time,...\r\n```bash\r\nopam init mingw \"https://github.com/fdopen/opam-repository-mingw.git\" --comp 4.01.0+mingw32 --switch 4.01.0+mingw32\r\n```\r\n"}],"action":{"name":"View Issue","url":"https://github.com/fdopen/opam-repository-mingw/issues/35#issuecomment-317192699"}}}

**Comment by cup** [comment]
https://github.com/fdopen/opam-repository-mingw/issues/35
https://github.com/fdopen/opam-repository-mingw/issues/43
https://github.com/fdopen/opam-repository-mingw/issues/67
