### ISSUE TITLE
Unable to install lablgtk

### ISSUE THREAD

**Issue by thranur** [fdopen/opam-repository-mingw#4]
I tried following your instructions precisely, but when trying to install `lablgtk`, I get this error:

```
[lablgtk: ./configure] Command started
[ERROR] The compilation of lablgtk failed at "./configure --prefix
        C:/cygwin32/home/user/.opam/4.02.3+mingw64
        LABLGLDIR=C:/cygwin32/home/user/.opam/4.02.3+mingw64/lib/lablgl".
[lablgtk: ocamlfind remove] Command started

#=== ERROR while compiling lablgtk.2.18.3 =====================================#
# opam-version         1.3.0~dev (6f1de674c5a19d48bcac0dc2610c5a9c42db6a51)
# os                   win32
# command              ./configure --prefix C:/cygwin32/home/user/.opam/4.02.3+mingw64 LABLGLDIR=C:/cygwin32/home/user/.opam/4.02.3+mingw64/lib/lablgl
# path                 C:/cygwin32/home/user/.opam/4.02.3+mingw64/build/lablgtk.2.18.3
# exit-code            1
# env-file             C:/cygwin32/home/user/.opam/4.02.3+mingw64/build/lablgtk.2.18.3\lablgtk-132-c743ac.env
# stdout-file          C:/cygwin32/home/user/.opam/4.02.3+mingw64/build/lablgtk.2.18.3\lablgtk-132-c743ac.out
# stderr-file          C:/cygwin32/home/user/.opam/4.02.3+mingw64/build/lablgtk.2.18.3\lablgtk-132-c743ac.err
### stdout ###
# [...]
# checking for suffix of executables... .exe
# checking whether we are cross compiling... no
# checking for suffix of object files... o
# checking whether we are using the GNU C compiler... yes
# checking whether x86_64-w64-mingw32-gcc.exe accepts -g... yes
# checking for x86_64-w64-mingw32-gcc.exe option to accept ISO C89... none needed
# checking platform... Win32
# checking native dynlink... checking for pkg-config... /home/user/.opam/4.02.3+mingw64/bin/pkg-config
# *** pkg-config too old; version 0.7 or better required.
# checking for GTK+ - version >= 2.0.0... no
# *** A new enough version of pkg-config was not found.
# *** See http://pkgconfig.sourceforge.net
### stderr ###
# Cannot exec pkg-config: No such file or directory
# configure: error: GTK+ is required



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  λ  build lablgtk 2.18.3
The following changes have been performed
  ∗  install camlp4     4.02+6
  ∗  install ocamlbuild 0

=-=- lablgtk.2.18.3 troubleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package requires gtk+ 2.0 development packages installed on your system
```

My `pkg-config` is indeed in the PATH, and I did nothing else than what's said in your instructions.

I did use `cygwinports` and managed to install for instance `zarith` using `depext`.

First I had tried using `4.02.3+mingw32c`, and got that same error message, so I noticed that in your page you listed the installed packages with `4.02.3+mingw64`, so I tried switching to it instead, but ended up with the same error.

Could you please just confirm that you can indeed install `lablgtk` normally? I wonder if some other package would have replaced `pkg-config` with a different version, or something similar, otherwise I fail to see why I'm having this problem.

**Comment by thranur** [comment]
I actually found it out: when running `strings` on my `pkg-config.exe` file, I noticed it contained a path to `i686-w64-mingw32-pkg-config` (for the 32-bit version). So I installed the `mingw64-i686-pkg-config` package via Cygwin and I was able to get it working!

Maybe it's just a missing entry in depext-cygwinports ?

Also, a similar error happened when trying to install `conf-gtksourceview`: `depext` worked but `install` didn't. It also pointed to pkg-config, so that's when I found it was the culprit.

**Comment by fdopen** [comment]
A normal `opam install` doesn't install external packages, you have to explicitly call 'opam depext'. `opam depext -i lablgtk` would have worked without any hassles. It would have installed gtk2 and pkg-config for you.

I will update the wrapper program for pkg-config to print a nice error message, that the user should install pkg-config with `opam depext conf-pkg-config`.

**Comment by thranur** [comment]
I did call `opam depext` before installing both `conf-gtksourceview` and `lablgtk`, and it did install most packages, but for some reason `i686-w64-mingw32-pkg-config` was not among them. All the other gtk dependences were installed. Hence why I had a hard time understanding this specific error...

**Comment by fdopen** [comment]
Ok,
1. the wrapper now explains how to install pkg-config ( https://github.com/fdopen/opam-repository-mingw/commit/33295ad487284e164d0a92d26300b7f9082ed067 , https://github.com/fdopen/depext-cygwinports/commit/bb1b6e2dbdc2a988eaa11b093c04aa7b217163b8 )
2. and I've added conf-pkg-config as an explicit dependency to a couple of packages that will use it ( https://github.com/fdopen/opam-repository-mingw/commit/94a43fa00d525225f7c6ddb6d8d9f6d4c983e4a5 )

**Comment by thranur** [comment]
This is just a comment for my future self (and anyone who happens to make the same mistake): `lablgtk` and `pkg-config` are **very** prickly, and forgetting one simple detail will lead to the dreaded "GTK+ not installed" error.

In my case, I forgot to save the modification to my PATH (adding `/usr/i686-w64-mingw32/sys-root/mingw/bin`), so I managed to install `lablgtk`, but after closing and re-opening my Cygwin terminal I couldn't install it anymore (e.g. after installing `conf-gtksourceview`). This is the kind of error that drives anyone crazy, so I'm noting it here explicitly just in case.

It might be even worthy adding the specific error message to your `README.md`, in case other people try searching for it on Google...
