### ISSUE TITLE
Suggestion: bundle Cygwin packages with the graphical installer

### ISSUE THREAD

**Issue by keleshev** [fdopen/opam-repository-mingw#44]
A small suggestion is to bundle the Cygwin packages together with the installer and then install them using `setup-x86.exe --quiet-mode --local-package-dir=...`, instead of prompting the user to select a mirror (some of them don't work, sometimes FTP is blocked, etc.).

My hope for the graphical installer is to be the easy-mode installer, where a user doesn't need to bother with these details.

**Comment by fdopen** [comment]
Some packages must be updated regularly. If the package with certificates is too old, https could fail. A Windows 10 update might even break cygwin itself (it already happened in the past). I don't have the time to monitor such issues and react instantly. And if bundled packages are too old, you could get problems in a later step, e.g. when depext-cygwinports tries to install additional packages (autoconf, pkg-config,...). cygwin's setup utility doesn't work well. Managing and enforcing version constraints is beyond its capabilities.

However, I've now tweaked the call of setup-x86_64.exe a little bit. If the default mirror also used by https://github.com/ocaml/ocaml-ci-scripts is [online](https://cygwin.com/mirrors.lst), cygwin's setup won't ask for anything.
