### ISSUE TITLE
Cannot link with ocamlsdl

### ISSUE THREAD

**Issue by Chimrod** [fdopen/opam-repository-mingw#47]
Hello,

I'm posting the issue here because I do not known where to find... I'm trying to build a project with ocamlsdl, but the compilation fails at the link stage.

Here is a minimal program 

```ocaml
let main () =
        print_endline "START:";
        Sdl.init [`VIDEO];
        Sdlvideo.set_video_mode [];
        Sdltimer.delay 2000;
        Sdl.quit ();
        print_endline "STOP!"

let _ = main ()
```

and the compilation line : `ocamlbuild -pkg sdl test.native` give this output : undefined reference to « wWinMain »

```
.../usr/x86_64-w64-mingw32/sys-root/mingw/lib/libmingw32.a(lib64_libmingw32_a-crt0_w.o) : Dans la fonction « wmain » :
/usr/src/debug/mingw64-x86_64-runtime-5.0.4-1/crt/crt0_w.c:23 : référence indéfinie vers « wWinMain »
collect2: error: ld returned 1 exit status
** Fatal error: Error during linking
```

The following packages have been installed with the cygwin package manager 

- libSDL{-devel,.1_2_0}
- libSDL_image{-devel,.1_2_0}
- libSDL_mixer{-devel,.1_2_0}
- libSDL_ttf{-devel,.1_2_0}
- mingw64-x86_64-SDL
- mingw64-x86_64-SDL_image
- mingw64-x86_64-SDL_mixer
- mingw64-x86_64-SDL_ttf

Thanks for your help :)

**Comment by fdopen** [comment]
ocamlsdl probably references the ascii runtime, while recent OCaml verions have switched to the unicode runtime.
Try it again with OCaml 4.05.0 or earlier.

**Comment by Chimrod** [comment]
Switching to 4.05.0 actually works fine. Thanks for answering so fast !
