### ISSUE TITLE
OPAM 2.0

### ISSUE THREAD

**Issue by db4** [fdopen/opam-repository-mingw#48]
[Main OPAM repository](https://github.com/ocaml/opam-repository) now requires `OPAM` 2.0:
```
[default] git+https://github.com/ocaml/opam-repository.git updated
[ERROR] The current version of OPAM cannot read the repository "default". 
        You should upgrade to at least version 2.0.

[ERROR] Could not fetch repo: OpamStd.OpamSys.Exit(66)
```
Do you have any plans to port the latest `OPAM` to Windows?

**Comment by fdopen** [comment]
There is now https://github.com/fdopen/opam-repository-mingw/tree/opam2
and https://github.com/fdopen/opam-repository-mingw/releases/tag/0.0.0.2

It's largely untested, I've justed ensured that my old merge scripts
work again (they use just a limited number of commands, I did neither
test any new OPAM 2.0 features nor the interactive usage from the
command line).

Feel free to test it yourself and report any problems in this thread.

**Comment by kkirstein** [comment]
I just tried the opam2 version, by running the installation script [opam64.tar.gz](https://github.com/fdopen/opam-repository-mingw/releases/download/0.0.0.2/opam64.tar.xz) in my existing Cygwin environment. I renamed the existing `.opam` folder beforehand, so no conversion of existing "switches" took place.

Everything seems to work fine, thanks for the great work!

**Comment by yakobowski** [comment]
I would suggest that you change the Github default branch to opam2, as it is the one who gets updated. This will be less surprising to users!

**Comment by fdopen** [comment]
Sounds like a good idea. `opam2` is now the default branch.
