### ISSUE TITLE
Documentation: opam init command line for "build from sources" identical to "install binaries"

### ISSUE THREAD

**Issue by MSoegtropIMC** [fdopen/opam-repository-mingw#56]
Dear Opam-MinGW Team,

on the installation page <https://fdopen.github.io/opam-repository-mingw/installation/> an opam init command line is given for "install precompiled" and for "compile it from source". As far as I can tell both command lines are identical.

Best regards,

Michael

**Comment by fdopen** [comment]
Thanks for reporting the issue.
Fixed in 58cf983dc8ca43e1c114358040b049d0ec81da58
