### ISSUE TITLE
Variable bin not found

### ISSUE THREAD

**Issue by ghost** [fdopen/opam-repository-mingw#58]
~~~
$ ocaml-env exec hello.ml
[ERROR] Variable bin not found
fatal error:$(opam config var bin) failed
~~~

**Comment by fdopen** [comment]
Does `opam config var bin` work, if you execute the command inside a regular cygwin shell?
If not, this is expected behaviour. This error can happen, if there is no opam switch or your switch is in an invalid state.

**Comment by ghost** [comment]
@fdopen um ok, so how to fix it?

**Comment by fdopen** [comment]
Just create a switch that works, e.g. with `opam switch create 4.08.0+mingw64c`

**Comment by ghost** [comment]
~~~
$ ocaml-env exec hello.ml
ocaml-env: internal error, uncaught exception:
           Unix.Unix_error(1, "create_process", "hello.ml")
~~~

**Comment by fdopen** [comment]
Well, you can't execute scripts under Windows, that only works under *nix. Try `ocaml-env exec ocaml hello.ml` instead. (And inside a cygwin terminal, you don't need `ocaml-env exec ...` at all, `ocaml hello.ml` is enough).

**Comment by cup** [comment]
that file doesnt exist...

~~~
$ find | grep ocaml
./bin/ocaml-env-win.exe
./bin/ocaml-env.exe
~~~
