### ISSUE TITLE
Repository updates

### ISSUE THREAD

**Issue by thranur** [fdopen/opam-repository-mingw#6]
I'd like to know how to ask for an update to a package that has already been updated on OPAM's "standard" repository; since yours is a fork from ocamlspotter, should I just send him a pull request and you'll update from him some time later? Should I send the pull request to you directly? Or there's no need to do anything, and periodically you'll be updating from their repositories?

**Comment by fdopen** [comment]
Ask here, camlspotters repository doesn't seem to be maintained any longer.

I run scripts to cherry picks commits from https://github.com/ocaml/opam-repository from time to time. But not all commits compile cleanly on windows and therefore they won't be merged. (And sometimes my scripts are too unsophisticated and I'm too lazy to correct it manually, ...)

**Comment by thranur** [comment]
Ok, thank you. I'm fixing one package that currently does not compile on Windows and when I get it done i'll send you a pull request.
