### ISSUE TITLE
Automated Installer Flags

### ISSUE THREAD

**Issue by mintsoft** [fdopen/opam-repository-mingw#61]
Hiya, I'm trying to automated some CI builds on Windows and I need to install into the environment in an unattended fashion. Usually `/S` or `/silent` etc works, however I can't find any flag to make the installer unattended, do they exist?

If they don't exist can you point me in the direction of the source code for the installer? Happy to implement such flags myself and contribute them back!

**Comment by fdopen** [comment]
Use the normal cygwin installer to install/update cygwin and then extract the archive. See e.g:

https://github.com/ocaml/ocaml-ci-scripts/blob/master/appveyor-install.ps1
https://github.com/ocaml/ocaml-ci-scripts/blob/master/appveyor-opam.sh
https://github.com/ocsigen/lwt/blob/master/appveyor.yml
https://github.com/coq/coq/blob/master/dev/ci/azure-opam.sh
