### ISSUE TITLE
Outdated doc page may be confusing searchers.

### ISSUE THREAD

**Issue by johnwhitington** [fdopen/opam-repository-mingw#65]
This page contains info and links to Jul 2019 installers:

https://fdopen.github.io/opam-repository-mingw/installation/

However, Google picks up this page first:

https://fdopen.github.io/opam-repository-mingw/

It talks about OCaml 4.03, which might lead people to think the project is out-of-date.

**Comment by fdopen** [comment]
Ok, I've announced 4.09.0. I will look for a better solution another time.
