### ISSUE TITLE
curl not working on manual install

### ISSUE THREAD

**Issue by DrYSG** [fdopen/opam-repository-mingw#70]
I am getting the same issue as: https://github.com/fdopen/opam-repository-mingw/issues/27

This is on a Windows 10 computer (the gui install failed, it could not install cygwin, probably a proxy issue, so I did a manual install of cygwin with all the needed packages.

```
$ bash opam64/install.sh
the following programs are not installed properly:
 curl
I can't proceed :(

```
On our computers, I need to run a local proxy (FACADE) so that I can get through the corporate proxy. So I have

HTTP_PROXY = http://localhost:3128

And lets me use git and many other programs.

Any suggestions (Other that to get I.T. to turn off the firewall, that will NEVER happen do to DOD requirements).

Oh yes,

```
$ curl --insecure --retry 2 --head "https://github.com"
Warning: Transient problem: timeout Will retry in 1 seconds. 2 retries left.

```

**Comment by fdopen** [comment]
curl also accepts environment variables for this purpose, e.g. http_proxy - see `man curl` for details. You just have to figure out, the right settings:

```bash
export http_proxy=....
bash  opam64/install.sh
```

Note: Windows environment variables are usually treated case-insensitive, but cygwin emulates linux behaviour.

**Comment by DrYSG** [comment]
Go figure. I only use HTTP_PROXY (all caps) on windows, and it works for all other programs (git, etc.) 
and today it started working for curl in cygwin, with no other changes to the system.

```
HTTP_PROXY=http://localhost:3128
```
