### ISSUE TITLE
Cannot install opam-mingw on cygwin 64

### ISSUE THREAD

**Issue by fithisux** [fdopen/opam-repository-mingw#8]
I followed the manual install path.

I am on latest cygwin on windows 10 x86_64.

opam init mingw 'https://github.com/fdopen/opam-repository-mingw.git' --comp 4.02.3+mingw64 --switch 4.02.3+mingw64

fails with error

OPAM has already been initialized.[ERROR] The compiler switch 4.02.3+mingw64 is not installed.

The last one is the dreaded one.

**Comment by fdopen** [comment]
Hmm,
it sounds like you've already used opam (or tried to use it). Rename your existing .opam directory and try it again:
```
$ mv -i ~/.opam ~/.opam.bak
$ opam init mingw 'https://github.com/fdopen/opam-repository-mingw.git' --comp 4.02.3+mingw64 --switch 4.02.3+mingw64
```

**Comment by fithisux** [comment]
Solved,

Thank you for your amazing work.
