### ISSUE TITLE
What's a good email to ask questions about long-term maintenance of opam-repository-mingw?

### ISSUE THREAD

**Issue by gasche** [fdopen/opam-repository-mingw#81]
Hi @fdopen,

I sent you an email on November 6th to ask about your maintenance plans for opam-repository-mingw, but I am not sure that I have the right email address (I used the one from your recent git commits). If you are fine receiving emails, could you give a correct email address here or write to me at <gabriel.scherer@gmail.com> or <gabriel.scherer@inria.fr>? If you are living in a post-email world, I can also just write my questions in the present issue, but they were not designed to be public.

**Comment by fdopen** [comment]
Yes, I've got your email. I'm just busy with other things. I will hopefully answer soon.
