### ISSUE TITLE
Add ocaml-variants.4.00.1+mingw64c

### ISSUE THREAD

**Issue by smorimoto** [fdopen/opam-repository-mingw#82]
I'm currently working on releasing the next stable version of setup-ocaml, but I noticed that `ocaml-variants.4.00.1+mingw64c` does not exist. Honestly, I don't think anyone will use that, but I think it's not a bad idea to officially say that the action supports "the OCaml 4.x series" by adding that. Could you add it?
https://github.com/fdopen/opam-repository-mingw/tree/opam2/packages/ocaml-variants

**Comment by smorimoto** [comment]
The action attempts to get the latest patch version as long as you use the wildcard character, so we don't have to think too much about other patch versions.
https://github.com/actions-ml/setup-ocaml/runs/1638043210?check_suite_focus=true

**Comment by fdopen** [comment]
Ok, I've added the compilers ( cdcfe61ec42e5c9c548384a5c071f79332445136 )
It's however not really useful. Other package descriptions are  usually not properly constraint for such old OCaml versions.

**Comment by smorimoto** [comment]
That said, thanks anyway!
