### ISSUE TITLE
Native Windows version

### ISSUE THREAD

**Issue by 89z** [fdopen/opam-repository-mingw#83]
It seems Cygwin is required for install:

https://fdopen.github.io/opam-repository-mingw/installation

Some might prefer a native Windows version

**Comment by fdopen** [comment]
* OCaml itself and many often used packages like ocamlfind or zarith require a posix shell and posix tools during their build process.
* opam internally also relies on tools that are not available as native windows version (e.g. rsync, git,...).

Therefore something like cygwin or wsl will be necessary in the foreseeable future 😟

**Comment by MyTDT-Mysoft** [comment]
we made our own optimized compiler!!!
but we are too lazy to compile tools for windows

and please stop recommending 64bit for windows... windows can do just fine with 32bit and 64bit, its NOT linux.

**Comment by 89z** [comment]
closing this because I don't care anymore
