### ISSUE TITLE
JFrog is going to close Bintray

### ISSUE THREAD

**Issue by smorimoto** [fdopen/opam-repository-mingw#87]
Perhaps we need to migrate to some alternative platform.
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by fdopen** [comment]
Yes,
thanks for reminding me about it.
It should be possible to upload the binaries to github instead (e.g. attach it to the tags https://github.com/fdopen/ocaml/releases ).
Or would this solution have any disadvantages? (e.g a github policy I don't know yet)

**Comment by smorimoto** [comment]
There is no major disadvantage, but it's a little different from the intended release usage, and GitHub should have had some rate limits for it, so use with CI may be problematic. Maybe @avsm can help with this. (I just sent a message on Slack about this.)

**Comment by avsm** [comment]
Uploading release binaries to GitHub shouldn't be a problem -- you just need to (as usual) make sure that for the project involved that the license terms are met and it's fine (e.g. for GPL code make the code associated with the binary available, that sort of thing)

**Comment by smorimoto** [comment]
Indeed!
