### ISSUE TITLE
Lablgl uses of X11R6 on x86_64-w64-mingw32

### ISSUE THREAD

**Issue by fithisux** [fdopen/opam-repository-mingw#9]
$ opam install lablgl
The following actions will be performed:
  ∗  install lablgl 1.05

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[lablgl: cp Makefile.config.ex] Command started
[lablgl: mkdir] Command started
[lablgl: make glut] Command started
[ERROR] The compilation of lablgl failed at "make glut".

#=== ERROR while compiling lablgl.1.05 ========================================#
# opam-version         1.3.0~dev (308be376d177c155c1f7f86a8ffaf621c9029836)
# os                   win32
# command              make glut
# path                 C:/langs/home/.opam/4.02.3+mingw64/build/lablgl.1.05
# exit-code            2
# env-file             C:/langs/home/.opam/4.02.3+mingw64/build/lablgl.1.05\lablgl-376-05296d.env
# stdout-file          C:/langs/home/.opam/4.02.3+mingw64/build/lablgl.1.05\lablgl-376-05296d.out
# stderr-file          C:/langs/home/.opam/4.02.3+mingw64/build/lablgl.1.05\lablgl-376-05296d.err
### stdout ###
# [...]
# ocamlc -pp camlp4o var2def.ml -o var2def
# ocamlc -pp camlp4o var2switch.ml -o var2switch
# /usr/bin/make lablgl.cma
# make[2]: Entering directory '/cygdrive/c/langs/home/.opam/4.02.3+mingw64/build/lablgl.1.05/src'
# ocamlrun ../src/var2def < gl_tags.var > gl_tags.h
# ocamlrun ../src/var2switch -table GL_ < gl_tags.var > gl_tags.c
# ocamlc -c -w s -ccopt "-c -O  -I/usr/X11R6/include" ml_gl.c
# ../Makefile.common:53: recipe for target 'ml_gl.o' failed
# make[2]: Leaving directory '/cygdrive/c/langs/home/.opam/4.02.3+mingw64/build/lablgl.1.05/src'
# Makefile:27: recipe for target 'all' failed
# make[1]: Leaving directory '/cygdrive/c/langs/home/.opam/4.02.3+mingw64/build/lablgl.1.05/src'
# Makefile:15: recipe for target 'lib' failed
### stderr ###
# ml_gl.h:28:23: note: in expansion of macro ‘Int_raw’
# [...]
#                        ^
# ml_gl.c:674:1: note: in expansion of macro ‘ML_2’
#  ML_2 (glGenTextures, Int_val, Int_raw)
#  ^
# In file included from ml_gl.c:10:0:
# /usr/x86_64-w64-mingw32/sys-root/mingw/include/GL/gl.h:782:25: note: expected ‘GLuint *’ but argument is of type ‘int *’
#  WINGDIAPI void APIENTRY glGenTextures(GLsizei n,GLuint *textures);
#                          ^
# make[2]: *** [ml_gl.o] Error 2
# make[1]: *** [all] Error 2
# make: *** [lib] Error 2

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  λ  build lablgl 1.05
No changes have been performed

=-=- lablgl.1.05 troubleshooting =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package relies on external (system) dependencies that may be missing.
   `opam depext lablgl.1.05' may help you find the correct installation for
   your system.

**Comment by fithisux** [comment]
Maybe one should do a

mv Makefileconfig.mingw Makefile.mingw

prior to compiling.

**Comment by fdopen** [comment]
Yes,
the package description was not yet updated for windows. I've pushed a new version (untested): https://github.com/fdopen/opam-repository-mingw/commit/e88dd67ed718764ff093c4671d02dbc483b8b796

You need depext-cygwinports in order to get freeglut:
```
opam update
opam install depext depext-cygwinports
opam depext -i lablgl
```

**Comment by fithisux** [comment]
Fixed
