### ISSUE TITLE
Windows Defender is flagging opam-putenv.exe as a "Trojan:Win32/Ymacco.AAF3".

### ISSUE THREAD

**Issue by AlanNicholasDay** [fdopen/opam-repository-mingw#91]
When attempting to install OCaml with the 64-bit Windows installer found here:
https://fdopen.github.io/opam-repository-mingw/installation/
Windows Defender flagged and quarantined opam-putenv.exe as a "Trojan:Win32/Ymacco.AAF3".

**Comment by fdopen** [comment]
Yes, I know. I've already removed it from `opam64.tar.xz` and `opam32.tar.xz`. I don't understand why it was still contained in 
`OCaml64.exe` and `OCaml32.exe`. But I've removed it know from there, too.

The file is not strictly necessary and it's flagged by too many antirvirus software. It would be too much work for me to contact all the antivirus manufacturers to have it classified as false-positive.
