### ISSUE TITLE
menhir, menhirLib and menhirSdk have bad checksum

### ISSUE THREAD

**Issue by smorimoto** [fdopen/opam-repository-mingw#93]
https://github.com/ocamllabs/vscode-ocaml-platform/runs/2617568131?check_suite_focus=true

**Comment by fdopen** [comment]
I've merged a62521e0d04814c32b0f9c3f7f51095847a09198.
I've also given you access to this repo now. Feel free to push such changes yourself, if you feel it is urgent.
